### ISSUE TITLE
Envoy crashing my server

### ISSUE THREAD

**Issue by VargasTheOne** [badbones69/Crazy-Envoy#13]
Every time i config the min crate location to 120 then reload then /envoy start itcrashes my server every time

**Comment by kicjow** [comment]
Then its because the range must be to much. Because of this I recommend using the random like this.
1. Set this to [false](https://github.com/kicjow/Crazy-Envoy/blob/master/Config.yml#L9).
2. Set this to [True](https://github.com/kicjow/Crazy-Envoy/blob/master/Config.yml#L7).
3. Save and reload.
4. Go in-game and use the /envoy edit and place a bunch of locations all over the map.
5. Then when you start it will pick random locations from the ones you placed.
