### ISSUE TITLE
Envoy commands 

### ISSUE THREAD

**Issue by star-kissed** [badbones69/Crazy-Envoy#44]
When I type any envoy commands nothing shows up in chat and nothing happens. This is only an issue when my tiers files are loaded instead of the default.

**Comment by star-kissed** [comment]
Fixed, just restarted the plugin

**Comment by Tradie18** [comment]
Turns out it's when we have these 4 crates in the directory. The plugin breaks.

I'm not the author of these crates so i wouldn't know what's the issue. Mind investigating someone? 

[Common.txt](https://github.com/badbones69/Crazy-Envoy/files/4239739/Common.txt)
[Epic.txt](https://github.com/badbones69/Crazy-Envoy/files/4239740/Epic.txt)
[Legendary.txt](https://github.com/badbones69/Crazy-Envoy/files/4239741/Legendary.txt)
[Rare.txt](https://github.com/badbones69/Crazy-Envoy/files/4239742/Rare.txt)
